# Generated by Django 5.2.7 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0002_rename_user_id_monthly_budget_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_budget',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recurring_bill',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='created_at',
        ),
    ]
