# Generated by Django 5.2.7 on 2025-11-06 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0004_categorymodel_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_budget',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_manager_app.categorymodel'),
        ),
    ]
