# Generated by Django 5.2.7 on 2025-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0011_remove_recurring_bill_recurring_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='payment_due',
            field=models.PositiveIntegerField(),
        ),
    ]
