# Generated by Django 5.2.7 on 2025-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0012_alter_recurring_bill_payment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_budget',
            name='budget_exact_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_budget',
            name='budget_exceed_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_budget',
            name='budget_four_fifth_exceeded_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
