# Generated by Django 5.2.7 on 2025-12-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0014_rename_budget_exceed_email_sent_monthly_budget_budget_exceeded_email_sent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monthly_budget',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='user_category_unique_constraint'),
        ),
    ]
