# Generated by Django 5.2.7 on 2025-12-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0017_alter_monthly_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_budget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance_manager_app.categorymodel'),
            preserve_default=False,
        ),
    ]
