# Generated by Django 6.0.8 on 2026-08-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance_manager_app",
            "0020_remove_monthly_budget_user_category_unique_constraint_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="recurring_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="finance_manager_app.recurring_bill",
            ),
        ),
    ]
