# Generated by Django 6.0.8 on 2026-08-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_manager_app", "0021_transaction_recurring_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurring_bill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_bills",
                to="finance_manager_app.categorymodel",
            ),
        ),
    ]
