# Generated by Django 6.0.8 on 2026-08-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_manager_app", "0022_alter_recurring_bill_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recurring_bill",
            old_name="amount",
            new_name="price",
        ),
    ]
