# Generated by Django 6.0.8 on 2026-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_manager_app", "0023_rename_amount_recurring_bill_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("expense", "expense"), ("income", "income")], max_length=8
            ),
        ),
    ]
